### ISSUE TITLE
Error aws lambda function when building with Mac AppleSilicon 

### ISSUE THREAD

**Issue by ennoucas** [Infisical/sdk#26]
When trying to deploy a AWS lambda function with NodeJs (Typescript) using Infisical SDK I get the following: 

> ✘ [ERROR] No loader is configured for ".node" files: asset-input/node_modules/@infisical/sdk-darwin-arm64/infisical.darwin-arm64.node
> 
>     asset-input/node_modules/@infisical/sdk/binding.js:141:36:
>       141 │             nativeBinding = require('@infisical/sdk-darwin-arm64')
>           ╵    

Command ran: `npx ts-node --prefer-ts-exts bin/sqs-lambda.ts`

Context
--
"@infisical/sdk": "^2.1.8",
Apple M2
MacOs Sonoma (14.3.1)

**Comment by DanielHougaard** [comment]
Hi @ennoucas, apologies for the delayed response.

This seems to be an issue with the building rather than the SDK. I found this Github Issue which seems to be referencing exactly the same issue as you're facing.

Here's a proposed solution to the issue: https://github.com/aws/aws-cdk/issues/18470#issuecomment-1425708187


Let me know if this works for you!
